# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "German Chapter der ScrumAlliance"
email: "kontakt@scrumdach.de"
description: "Das German Chapter der ScrumAlliance ist die Interessensvertretung der deutschsprachigen Mitglieder aus D-A-CH."
baseurl: "/scrumdach"
url: "http://www.scrumdach.de"

# Organizer Info
organizerName: "German Chapter der Scrum Alliance"
organizerAlternateName: "Scrum Alliance D-A-CH Chapter"
organizerDescription: "Das German Chapter der ScrumAlliance ist die Interessensvertretung der deutschsprachigen Mitglieder aus D-A-CH."
organizerEmail: "kontakt@scrumdach.de"
organizerLink: "http://www.scrumdach.camp/"

# Head
metaKeywords: "scrumalliance, scrum, agile, scrum gathering, gathering, coaching, training, scrum master, product owner, developer"
twitterAccount: "@scrumdach"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Sessions"}
# - {permalink: "/speakers/", text: "Referenten"}
# - {permalink: "/team/", text: "Team"}
# bottomNavigationLinks:
# - {link: "./schedule/", text: "Zur Agenda >>>"}
# - {link: "http://de.amiando.com/ZDVKXIJ.html", text: "Ticket(s) kaufen"}
# rightNavigationButtons:
# - {link: "./schedule/", text: "Zur Agenda >>>"}
# - {link: "http://de.amiando.com/ZDVKXIJ.html", text: "Ticket(s) kaufen"}

# Hero Block
heroImage: "open_space_sgmun_dunkel.jpg"
heroTitle: "Scrum<typeout> "
eventDate: "Dein Zugang zur deutschsprachigen Scrum - Community"
typeoutTextValues: '"", " Community Deutschland", " Community Österreich", " Community Schweiz", " Community D-A-CH", " Gathering Regional"'
typeoutFallback: "Alliance :: D-A-CH Chapter"
heroButtons:
 - {link: "http://bit.ly/2mDvj6c", text: "Weiter zu den Community - Seiten der Scrum Alliance >>>"}
# - {link: "http://de.amiando.com/ZDVKXIJ.html", text: "Ticket(s) kaufen"}

# About Block
aboutTitle: "Warum eigentlich ein deutschsprachiges Chapter der Scrum Alliance, ein D-A-CH Chapter?"
aboutBlock:
 - {title: "", image: "conference.jpg", text: "Wir möchten die Interessen der Community aus der Region D-A-CH besser in Richtung Scrum Alliance (US) vertreten & der Scrum Alliance hier ein Gesicht geben!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "23", specialCharacter: "+", info: "CST/CEC/CTC", detail: "Experten auf Enterprise-Ebene für Training & Coaching"}
 - {count: "345", specialCharacter: "+", info: "CSP", detail: "Professionals mit mehrjähriger praktische Erfahrung"}
 - {count: "8036", specialCharacter: "+", info: "CSM/CSPO/CSD", detail: "in Deutschland, Österreich und der Schweiz"}
 - {count: "87", specialCharacter: "+", info: "User Groups", detail: "Lokaler Austausch zu den Themen Scrum & Agilität"}
 - {count: "10", specialCharacter: "+", info: "Arbeitsgruppen", detail: "Überregionale Zusammenarbeit an wertvollen Themen'"}

# Latest News Block
latestNewsTitle: "Neuigkeiten"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 6
rockstarSpeakersTitle: "Rockstars der modernen Arbeitswelt"
rockstarSpeakersButtonText: "Wer spricht alles auf dem den freiräume.camp 2015?"

# Location Block
locationBlockTitle: "Wo?"
eventLocationName: "Haus der Wirtschaftsförderung"
eventLocationLink: "http://www.wirtschaftsfoerderung-hannover.de"
eventStreetAddress: "Vahrenwalder Str. 7"
eventAddressLocality: "Hannover"
eventAddressLocalityRegion: "Niedersachsen"
eventPostalCode: "30165"
eventAddressCountry: "Deutschland"
eventStartTime: "2015-05-29T09:30"
eventDoorTime: "09:00"
eventEndTime: "2015-10-30T17:00"
eventPlaceCoordinates: "52.386168, 9.733600"
mapCenterCoordinates: "52.386168, 9.733600"
mapMobileCenterCoordinates: "52.386168, 9.733600"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Was geht?"
twitterHashTag: "frrm15"

# Tickets Block
ticketsTitle: "Ticketpreis(e)"
ticketsInfo: "Mit dem Ticket kannst Du am freiräume.camp 2015 teilnehmen. Catering ist dabei inklusive. Das einzige, was Du selbst tragen musst, sind Deine Reisekosten ;)"
ticketsOffers:
 -
  name: "Frühbucher"
  price: "49,-"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  ribbon: "-25%"
  buyButtonLink: "http://de.amiando.com/ZDVKXIJ.html"
  buyButtonText: "Ausverkauft"
  validFrom: "2015-04-01T10:00"
  validThrough: "2015-04-30T23:59"
  disabled: true
 -
  name: "Normal"
  price: "65,-"
  priceCurrency: "EUR"
  ticketsNumber: "100"
  featured: true
  buyButtonLink: "http://de.amiando.com/ZDVKXIJ.html"
  buyButtonText: "Ausverkauft"
  validFrom: "2015-05-01T10:00"
  validThrough: "2015-05-28T23:59"
  disabled: true

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=freiraumcamp", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/freiraumcamp-2015-Konferenz-und-Barcamp-f%C3%BCr-moderne-Arbeitswelten/1567028996917350", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Kontakt"
  links:
   - {link: "mailto:kontakt@freiraum.camp", text: "kontakt@freiraum.camp"}
 -
  title: "Weiteres"
  links:
   - {permalink: "/imprint/", text: "Impressum"}

# Blog
blogTitle: "Neuigkeiten"
blogCommentsEnabled: false
discusShortName: "freiraum"
